project_id = "majqoqagohicjigmsilu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.send-admin-invitation]
verify_jwt = false

[functions.create-team-member]
verify_jwt = true

[auth]
enabled = true
external_anonymous_users_enabled = true