triggers:
  - name: student_created
    event: student.created
    action:
      type: email
      smtp_purpose: lms
      template: student-welcome
      subject: "Welcome to the LMS"
      retry:
        max_attempts: 3
        backoff: exponential
        initial_delay: 300000  # 5 minutes
        smtp_config_retry_delay: 3600000  # 1 hour for missing config

  - name: staff_created
    event: staff.created
    action:
      type: email
      smtp_purpose: lms
      template: staff-welcome
      subject: "Your LMS Login Details"
      retry:
        max_attempts: 3
        backoff: exponential
        initial_delay: 300000  # 5 minutes
        smtp_config_retry_delay: 3600000  # 1 hour for missing config

  - name: invoice_created
    event: invoice.created
    condition: recipient_type == 'student'
    action:
      type: email
      smtp_purpose: billing
      template: student-invoice
      subject: "Invoice #{{invoice_number}}"
      retry:
        max_attempts: 3
        backoff: exponential
        initial_delay: 300000  # 5 minutes
        smtp_config_retry_delay: 3600000  # 1 hour for missing config

audit:
  enabled: true
  log_events:
    - mail.sent
    - mail.failed
    - mail.retry
  fields:
    - purpose
    - to
    - template
    - status
    - attempt
    - error_type